import { useState } from "react";
import { FiCompass, FiLogOut, FiMenu, FiMoon, FiSun, FiUser, FiX } from "react-icons/fi";
import { Link, NavLink, useNavigate } from "react-router-dom";
import { useTheme } from "../context/ThemeContext";
import { useAuth } from "../context/AuthContext";

const links = [{ to: "/", label: "Home" }, { to: "/destinations", label: "Destinations" }, { to: "/planner", label: "AI Planner" }, { to: "/about", label: "About" }];

function Navbar() {
  const [open, setOpen] = useState(false);
  const { isDark, toggleTheme } = useTheme();
  const { user, isAuthenticated, logout } = useAuth();
  const navigate = useNavigate();
  const signOut = () => { logout(); setOpen(false); navigate("/"); };
  const linkClass = ({ isActive }) => `rounded-lg px-3 py-2 text-sm font-semibold transition ${isActive ? "bg-sky-50 text-sky-700" : "text-slate-600 hover:bg-slate-50 hover:text-sky-700"}`;
  const themeButton = <button type="button" onClick={toggleTheme} aria-label={`Switch to ${isDark ? "light" : "dark"} mode`} aria-pressed={isDark} className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200 bg-white text-slate-700 shadow-sm transition hover:-translate-y-0.5 hover:border-sky-300 hover:text-sky-700">{isDark ? <FiSun /> : <FiMoon />}</button>;
  const accountLinks = isAuthenticated ? <><NavLink to="/saved-trips" className="rounded-xl px-3 py-2 text-sm font-bold text-slate-600 transition hover:bg-rose-50 hover:text-rose-700">Saved Trips</NavLink><NavLink to="/trip-history" className="rounded-xl px-3 py-2 text-sm font-bold text-slate-600 transition hover:bg-sky-50 hover:text-sky-700">Trip History</NavLink><NavLink to="/profile" className="ml-2 inline-flex items-center gap-2 rounded-xl bg-sky-700 px-4 py-2 text-sm font-bold text-white shadow-sm transition hover:bg-sky-800"><FiUser /> {user?.firstName || "My Profile"}</NavLink><button type="button" onClick={signOut} className="inline-flex items-center gap-1 rounded-xl px-3 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-100"><FiLogOut /> Logout</button></> : <><NavLink to="/login" className="ml-2 rounded-xl px-3 py-2 text-sm font-bold text-sky-700 transition hover:bg-sky-50">Login</NavLink><NavLink to="/signup" className="rounded-xl bg-sky-700 px-4 py-2 text-sm font-bold text-white shadow-sm transition hover:bg-sky-800">Sign Up</NavLink></>;
  return <header className="sticky top-0 z-30 border-b border-slate-100 bg-white/95 backdrop-blur"><nav className="mx-auto flex max-w-7xl items-center justify-between px-4 py-3 sm:px-6"><Link to="/" className="flex items-center gap-2 font-bold tracking-tight text-slate-900"><span className="grid h-9 w-9 place-items-center rounded-xl bg-gradient-to-br from-sky-500 to-blue-700 text-white shadow-lg shadow-sky-600/25"><FiCompass /></span><span>India Tourism <span className="text-sky-700">AI</span></span></Link><div className="hidden items-center gap-1 md:flex">{links.map((link) => <NavLink key={link.to} to={link.to} className={linkClass}>{link.label}</NavLink>)}{themeButton}{accountLinks}</div><div className="flex items-center gap-2 md:hidden">{themeButton}<button type="button" className="rounded-lg p-2 text-slate-700" onClick={() => setOpen((value) => !value)} aria-label="Toggle navigation">{open ? <FiX className="h-5 w-5" /> : <FiMenu className="h-5 w-5" />}</button></div></nav>{open && <div className="border-t border-slate-100 bg-white px-4 py-3 md:hidden"><div className="mx-auto flex max-w-7xl flex-col gap-1">{links.map((link) => <NavLink key={link.to} to={link.to} onClick={() => setOpen(false)} className={linkClass}>{link.label}</NavLink>)}{isAuthenticated ? <><NavLink to="/saved-trips" onClick={() => setOpen(false)} className={linkClass}>Saved Trips</NavLink><NavLink to="/trip-history" onClick={() => setOpen(false)} className={linkClass}>Trip History</NavLink><NavLink to="/profile" onClick={() => setOpen(false)} className={linkClass}>My Profile</NavLink><button type="button" onClick={signOut} className="rounded-lg px-3 py-2 text-left text-sm font-semibold text-slate-600">Logout</button></> : <><NavLink to="/login" onClick={() => setOpen(false)} className={linkClass}>Login</NavLink><NavLink to="/signup" onClick={() => setOpen(false)} className="mt-1 rounded-xl bg-sky-700 px-4 py-2 text-center text-sm font-bold text-white">Sign Up</NavLink></>}</div></div>}</header>;
}

export default Navbar;
