import { Link } from "react-router-dom";
import { FiArrowRight, FiBriefcase, FiClock, FiCompass, FiFileText, FiHeart, FiMapPin, FiPlus } from "react-icons/fi";
import SiteLayout from "../components/SiteLayout";
import { useAuth } from "../context/AuthContext";

const stats = [
  { label: "Saved Trips", value: 0, icon: FiHeart, tone: "bg-rose-50 text-rose-600", to: "/saved-trips" },
  { label: "Planned Trips", value: 0, icon: FiBriefcase, tone: "bg-sky-50 text-sky-700", to: "/trip-history" },
  { label: "Downloaded PDFs", value: 0, icon: FiFileText, tone: "bg-amber-50 text-amber-600", to: "/trip-history" },
  { label: "Recently Viewed", value: 0, icon: FiMapPin, tone: "bg-emerald-50 text-emerald-600", to: "/destinations" },
];

function Dashboard() {
  const { user } = useAuth();
  return <SiteLayout><main className="min-h-[70vh] bg-gradient-to-b from-sky-50 via-white to-indigo-50/40 px-4 py-8 sm:px-6 sm:py-10"><div className="mx-auto max-w-6xl"><section className="relative overflow-hidden rounded-[2rem] bg-gradient-to-br from-sky-700 via-blue-700 to-indigo-800 p-7 text-white shadow-xl shadow-blue-900/20 sm:p-10"><div className="absolute -right-16 -top-20 h-64 w-64 rounded-full bg-sky-300/20 blur-3xl" /><div className="relative"><p className="text-sm font-bold uppercase tracking-[.16em] text-sky-200">Your travel space</p><h1 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">👋 Welcome back, {user?.firstName || "Traveler"}!</h1><p className="mt-3 max-w-xl leading-7 text-sky-100">Your next great Indian journey starts with a simple plan.</p><Link to="/planner" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3 font-bold text-sky-800 shadow-lg transition hover:-translate-y-0.5 hover:shadow-xl"><FiPlus /> Plan New Trip <FiArrowRight /></Link></div></section>
    <section className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{stats.map(({ label, value, icon: Icon, tone, to }) => <Link key={label} to={to} className="group rounded-3xl border border-slate-100 bg-white p-5 shadow-sm transition hover:-translate-y-1 hover:border-sky-200 hover:shadow-lg"><span className={`grid h-11 w-11 place-items-center rounded-2xl ${tone}`}><Icon /></span><p className="mt-5 text-3xl font-bold text-slate-900">{value}</p><p className="mt-1 text-sm font-semibold text-slate-600">{label}</p></Link>)}</section>
    <section className="mt-7 grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><div className="rounded-3xl border border-slate-100 bg-white p-6 shadow-sm sm:p-7"><div className="flex items-center justify-between"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-sky-700">Keep exploring</p><h2 className="mt-1 text-2xl font-bold text-slate-900">Quick Actions</h2></div><FiCompass className="text-xl text-sky-600" /></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><Link to="/planner" className="rounded-2xl bg-sky-50 p-4 text-sm font-bold text-sky-800 transition hover:bg-sky-100"><FiPlus className="mb-3 text-lg" />Plan New Trip</Link><Link to="/destinations" className="rounded-2xl bg-indigo-50 p-4 text-sm font-bold text-indigo-800 transition hover:bg-indigo-100"><FiCompass className="mb-3 text-lg" />Explore Destinations</Link><a href="https://www.google.com/travel/" target="_blank" rel="noreferrer" className="rounded-2xl bg-emerald-50 p-4 text-sm font-bold text-emerald-800 transition hover:bg-emerald-100"><FiBriefcase className="mb-3 text-lg" />Travel Booking Hub</a></div></div><div className="rounded-3xl border border-slate-100 bg-white p-6 shadow-sm sm:p-7"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-slate-100 text-slate-600"><FiClock /></span><div><p className="text-sm font-bold uppercase tracking-[.16em] text-sky-700">Your journey</p><h2 className="mt-1 text-2xl font-bold text-slate-900">Recent Activity</h2></div></div><div className="mt-6 rounded-2xl border border-dashed border-slate-200 bg-slate-50 p-5 text-center"><FiMapPin className="mx-auto text-xl text-slate-400" /><p className="mt-3 font-semibold text-slate-700">No activity yet</p><p className="mt-1 text-sm leading-6 text-slate-500">Create your first AI trip plan to see it here.</p></div></div></section>
  </div></main></SiteLayout>;
}
export default Dashboard;
