import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { FiArrowRight, FiEye, FiEyeOff, FiLock, FiMail, FiUser } from "react-icons/fi";
import { useAuth } from "../context/AuthContext";
import api from "../services/api";
import SiteLayout from "../components/SiteLayout";

const inputClass = "w-full rounded-xl border border-white/20 bg-white/70 py-3 pl-11 pr-4 text-slate-800 outline-none transition placeholder:text-slate-400 focus:border-sky-500 focus:bg-white focus:ring-4 focus:ring-sky-200/60";
function Signup() {
  const [form, setForm] = useState({ firstName: "", lastName: "", email: "", password: "", confirmPassword: "" }); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const [showPassword, setShowPassword] = useState(false); const navigate = useNavigate(); const { setAuth } = useAuth();
  const update = (event) => setForm((current) => ({ ...current, [event.target.name]: event.target.value }));
  const submit = async (event) => { event.preventDefault(); setError(""); if (form.password !== form.confirmPassword) return setError("Passwords do not match."); if (form.password.length < 8) return setError("Password must be at least 8 characters."); setLoading(true); try { const { data } = await api.post("/auth/signup", form); setAuth(data); navigate("/", { replace: true }); } catch (requestError) { setError(requestError.response?.data?.message || "Unable to create your account."); } finally { setLoading(false); } };
  return <SiteLayout><AuthShell title="Create your travel account" subtitle="Save your travel identity and start planning with confidence."><form onSubmit={submit} className="mt-6 space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Input icon={FiUser} name="firstName" value={form.firstName} onChange={update} placeholder="First name" autoComplete="given-name" /><Input icon={FiUser} name="lastName" value={form.lastName} onChange={update} placeholder="Last name" autoComplete="family-name" /></div><Input icon={FiMail} name="email" type="email" value={form.email} onChange={update} placeholder="Email address" autoComplete="email" /><PasswordInput name="password" value={form.password} onChange={update} placeholder="Password (8+ characters)" show={showPassword} toggle={() => setShowPassword(!showPassword)} autoComplete="new-password" /><PasswordInput name="confirmPassword" value={form.confirmPassword} onChange={update} placeholder="Confirm password" show={showPassword} toggle={() => setShowPassword(!showPassword)} autoComplete="new-password" />{error && <p role="alert" className="rounded-xl bg-rose-50 px-4 py-3 text-sm font-medium text-rose-700">{error}</p>}<Submit loading={loading}>Create account <FiArrowRight /></Submit></form><p className="mt-6 text-center text-sm text-slate-600">Already have an account? <Link className="font-bold text-sky-700 hover:text-sky-900" to="/login">Sign in</Link></p></AuthShell></SiteLayout>;
}
export function AuthShell({ title, subtitle, children }) { return <main className="relative grid min-h-[calc(100vh-8rem)] place-items-center overflow-hidden px-4 py-10"><div className="absolute inset-0 -z-10 bg-gradient-to-br from-sky-100 via-white to-indigo-100" /><div className="absolute -left-24 top-16 -z-10 h-72 w-72 rounded-full bg-sky-400/30 blur-3xl" /><section className="w-full max-w-lg rounded-[2rem] border border-white/60 bg-white/70 p-6 shadow-2xl shadow-sky-900/10 backdrop-blur-xl sm:p-8"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-gradient-to-br from-sky-500 to-indigo-700 text-xl text-white shadow-lg shadow-sky-600/25">✈</div><h1 className="mt-5 text-3xl font-bold tracking-tight text-slate-900">{title}</h1><p className="mt-2 leading-6 text-slate-600">{subtitle}</p>{children}</section></main>; }
export function Input({ icon: Icon, ...props }) { return <div className="relative"><Icon className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" /><input required className={inputClass} {...props} /></div>; }
export function PasswordInput({ show, toggle, ...props }) { return <div className="relative"><FiLock className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" /><input required type={show ? "text" : "password"} className={inputClass} {...props} /><button type="button" onClick={toggle} className="absolute right-3 top-1/2 -translate-y-1/2 rounded-lg p-1.5 text-slate-400 hover:text-sky-700" aria-label={show ? "Hide password" : "Show password"}>{show ? <FiEyeOff /> : <FiEye />}</button></div>; }
export function Submit({ loading, children }) { return <button disabled={loading} className="flex w-full items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-sky-600 to-indigo-700 px-4 py-3.5 font-bold text-white shadow-lg shadow-sky-700/25 transition hover:-translate-y-0.5 hover:shadow-xl disabled:cursor-wait disabled:opacity-70">{loading ? <><span className="h-5 w-5 animate-spin rounded-full border-2 border-white/35 border-t-white" /> Please wait…</> : children}</button>; }
export default Signup;
